### ISSUE TITLE
Breaks on github link packages

### ISSUE THREAD

**Issue by isurfbecause** [meain/vim-package-info#25]
Hi,

I am experiencing breaking issues in `package.json`. The version numbers will populate until it gets to a npm module referencing our private github repo.

![image](https://user-images.githubusercontent.com/1476109/60542228-4108d180-9cc8-11e9-8e20-965ee1fc6589.png)

**Comment by meain** [comment]
@isurfbecause , thank you for reporting the issue.

This happens because we were just expecting the right side to be a version number and nothing else. This is the version number that we were comparing the latest version against.

Ideal solution will be to parse the `lockfile` to find the exact current version, which is something that I  have been putting aside for some time now. As a quick fix we could just skip the version check for these ones.

Let me see if I can work on it, I am just a bit busy these days. Any PR's are welcome.
